server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        enable_lazy_load_no_trans: true
    show-sql: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  datasource:
    url: jdbc:postgresql://localhost:5432/ewallet
    username: postgres
    password: andela

app:
  jwt:
    secret: tekanaeWalletJwtSecretKey
  authorities:
    USER: USER
    ADMIN: ADMIN

  baseUrl: "http://localhost"